In [22]:
from numpy import matrix
from numpy import random

### Create matrix A with size (3,5) containing random numbers 

In [29]:
A=matrix(random.randint(low=0, high=100, size=(3,5)))
A

matrix([[96, 81, 22, 37, 68],
        [70, 33, 51, 64, 85],
        [90, 67, 67,  5, 93]])

### Find the size and length of matrix A

In [30]:
A.shape

(3, 5)

### Resize (crop/slice) matrix A to size (3,4)

In [31]:
A=A[0:3, 0:4]
A

matrix([[96, 81, 22, 37],
        [70, 33, 51, 64],
        [90, 67, 67,  5]])

In [32]:
A.shape

(3, 4)

### Find the transpose of matrix A and assign it to B

In [105]:
B=A.T
B

matrix([[96, 70, 90],
        [81, 33, 67],
        [22, 51, 67],
        [37, 64,  5]])

In [34]:
B.shape

(4, 3)

### Find the minimum value in column 1 of matrix B

In [49]:
B[:,0].min()

22

### Find the minimum and maximum values for the entire matrix A

In [53]:
print(A.max(), A.min())

96 5


### Create vector X (an array) with 4 random numbers

In [74]:
X=random.randint(0,100, size=(1,4))[0]

In [75]:
X

array([80, 82, 83, 50])

### Create a function and pass vector X and matrix A in it, in the new function multiply vector X with matrix A and assign the result to D 

In [79]:
def vectorMatrixMul(X,A):
    return np.matmul(A,X)

In [80]:
D=vectorMatrixMul(X,A)

In [81]:
D

matrix([[17998, 15739, 18505]])

### Create a complex number Z with absolute and real parts != 0, Show its real and imaginary parts as well as it’s absolute value

In [89]:
Z=1.2 + 1j

In [94]:
print(f'real: {Z.real}, imag: {Z.imag}, abs: {np.abs(Z)}')

real: 1.2, imag: 1.0, abs: 1.5620499351813308


### Multiply result D with the absolute value of Z and record it to C

In [99]:
C=Z.real*D
C

matrix([[21597.6, 18886.8, 22206. ]])

### Convert matrix B from a matrix to a string and overwrite B

In [109]:
B=np.array_str(B)

In [110]:
print(B)

[[96 70 90]
 [81 33 67]
 [22 51 67]
 [37 64  5]]


Display a text on the screen: `Name is done with HW2`, but pass your `Name` as a string variable

In [111]:
Name='Rashmi'
f'{Name} is done with HW2'

'Rashmi is done with HW2'